GameReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("contact/", include("contact.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path("", include("games.urls")),
]


if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

games/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("", views.GamesView.as_view(), name="main_page"),
	path("filter/", views.FilterGamesView.as_view(), name='filter'),
	path("search/", views.Search.as_view(), name='search'),
	path("add-rating/", views.AddStarRating.as_view(), name='add_rating'),

	path("genre/<slug:slug>/", views.GenreView.as_view(), name="genre_view"),
	path("<slug:slug>/", views.GameDetailView.as_view(), name="game_detail"),



	path("review/<int:pk>/", views.AddReview.as_view(), name="add_review"),
	path("developer/<str:slug>/", views.DeveloperView.as_view(), name="developer_detail"),

]

games/models.py
from django.db import models
from datetime import date
from django.urls import reverse

class Category(models.Model):
    """Возрастной рейтинг"""
    name = models.CharField("Возрастной рейтинг", max_length=150)
    age = models.CharField('Разрешенный возраст', max_length=20)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

class Genre(models.Model):
    """Жанр"""
    name = models.CharField("Жанр", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)
	

    def get_absolute_url(self):
        return reverse('genre_detail', kwargs={"slug": self.url})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"
		

class Developer(models.Model):
    """Разработчик и издатель"""
    name = models.CharField('Имя', max_length=100)
    date = models.DateField('Дата основания', default=date.today)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to="developers/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('developer_detail', kwargs={"slug": self.name})


    class Meta:
        verbose_name = "Разработчик и издатель"
        verbose_name_plural = "Разработчики и издатели"

class Game(models.Model):
    """Игры"""
    title = models.CharField("Название", max_length=100)
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="posters/")
    date = models.DateField("Дата выхода", default=date.today)
    year = models.PositiveSmallIntegerField("Год выхода", default=2021)
    developer = models.ManyToManyField(Developer,verbose_name='разработчик', related_name="game_developer")
    publisher = models.ManyToManyField(Developer,verbose_name='издатель', related_name="game_publisher")
    category = models.ManyToManyField(Category, verbose_name="категории")
    genre = models.ManyToManyField(Genre, verbose_name="жанр")
    url = models.SlugField(max_length=130, unique=True)
    trailer = models.CharField("Трейлер", max_length=200, blank=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("game_detail", kwargs={"slug": self.url})

    def get_review(self):
        return self.reviews_set.filter(parent__isnull=True)


    class Meta:
        verbose_name = "Игра"
        verbose_name_plural = "Игры"



class GameShots(models.Model):
    """Кадры из игры"""
    title = models.CharField('Заголовок', max_length=100)
    description = models.TextField('Описание')
    image = models.ImageField('Изображение', upload_to="game_shots/") 
    game = models.ForeignKey(Game, verbose_name="Игры", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из игры"
        verbose_name_plural = "Кадры из игр"     

class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.PositiveSmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""

    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE,verbose_name="звезда")
    game = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name="игра")
    user = models.CharField("Имя пользователя", max_length=150)

    def __str__(self):
        return f"{self.star} - {self.game}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey('self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True)
    game = models.ForeignKey(Game, verbose_name="игра", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.game}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

games/forms.py
from django import forms

from .models import Reviews, Rating, RatingStar

class ReviewForm(forms.ModelForm):
	"""Форма отзывов"""
	class Meta:
		model = Reviews
		fields = ("name", "email", "text")

class RatingForm(forms.ModelForm):
    """Форма добавления рейтинга"""
    star = forms.ModelChoiceField(
        queryset=RatingStar.objects.all(), widget=forms.RadioSelect(), empty_label=None
    )

    class Meta:
        model = Rating
        fields = ("star",)			

games/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Q, Avg
from django.http import JsonResponse

from .models import Game, Genre, Category, Developer
from .forms import ReviewForm, RatingForm, Rating
# Create your views here.

class GenreYear:
    """Жанры и года выхода фильмов"""
    def get_genres(self):
        return Genre.objects.all()

    def get_years(self):
        return Game.objects.filter(draft=False).order_by('year').values("year").distinct()
		

class GamesView(GenreYear, ListView):
	"""Список игр"""
	model = Game
	queryset = Game.objects.filter(draft=False)
	template_name = "game/games.html"

	paginate_by = 10




class GameDetailView(GenreYear, DetailView):
    """Полное описание игры"""
    model = Game
    slug_field = "url"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["star_form"] = RatingForm()
        return context

class GenreView(GenreYear, DetailView):
    model = Genre
    template_name = "games/genre.html"
    slug_field = "url"


class AddReview(View):
	"""Отзывы"""
	def post(self, request, pk):
		form = ReviewForm(request.POST)
		game = Game.objects.get(id=pk)
		if form.is_valid():
			form = form.save(commit=False)
			if request.POST.get("parent", None):
				form.parent_id = int(request.POST.get("parent"))
			form.game_id = pk
			form.save() 

		return redirect(game.get_absolute_url())

class DeveloperView(GenreYear, DetailView):
	"""Полное описание разработчика или публ"""
	model = Developer
	template_name = 'games/developer.html'
	slug_field = "name"

class FilterGamesView(GenreYear, ListView):
    """Фильтр игр"""
    paginate_by = 6

    def get_queryset(self):
        queryset = Game.objects.filter(
            Q(year__in=self.request.GET.getlist("year")) |
            Q(genre__in=self.request.GET.getlist("genre"))
        ).distinct()
        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["year"] = ''.join([f"year={x}&" for x in self.request.GET.getlist("year")])
        context["genre"] = ''.join([f"genre={x}&" for x in self.request.GET.getlist("genre")])
        return context

class AddStarRating(View):
    """Добавление рейтинга фильму"""
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                game_id=int(request.POST.get("game")),
                user=request.POST.get("username"),
                defaults={'star_id': int(request.POST.get("star"))},

            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)



        

class Search(ListView):
    """Поиск фильмов"""
    paginate_by = 4

    def get_queryset(self):
        return Game.objects.filter(title__icontains=self.request.GET.get("q"))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["q"] = f'q={self.request.GET.get("q")}&'
        return context

templates/games/developer.html
{% extends 'games/games_base.html'%} {% load static %} {% block title %} GR | {{ developer.name }} {% endblock title%} {% block container %}
<div class="container py-md-3">
    {% endblock container %} {% block game %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ developer.image.url }}" class="img-fluid" alt="">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <div class="OdnaName" style="outline: none; cursor: inherit;">
                    {{ developer.name }}
                </div>
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><div class="desc1-right-b">Год:</div>
                            <div class="desc1-right-b-two">
                                {{ developer.date }}</div></span>

                        <li style="list-style: none">
                            <span><div class="desc1-right-b">Разработчик:</div>
                                <div class="desc1-right-b-two">
                                    {% for game in developer.game_developer.all %}
                                {{ game.title }};
                                {% endfor %}
                            </div>
                            </span>


                        </li>
                        <li style="list-style: none">
                            <span><div class="desc1-right-b">Издатель:</div>
                                <div class="desc1-right-b-two">
                                    {% for game in developer.game_publisher.all %}
                                {{ game.title }};
                                {% endfor %}
                            </div>

                                
                            
                            </span>
                        </li>
                </ul>
            </div>
        </div>
        <div class="row sub-para-w3layouts mt-5">
            <h3 class="shop-sing editContent">
                О {{ developer.name }}
            </h3>
            <p class="shop-sing-opis">
                {{ developer.description|safe }}
            </p>
        </div>
    </div>
    {% endblock game%}

templates/games/game_detail.html
{% extends 'games/games_base.html'%}
{% load static %}
{% block title %} GR | {{ game.title }} {% endblock title%}

        {% block game %}
        <div class="left-ads-display col-lg-8">
            <div class="row">
                <div class="desc1-left col-md-6">
                    <img src="{{ game.poster.url }}" class="img-fluid-detail" alt="">
                </div>
                <div class="desc1-right col-md-6 pl-lg-4">
                    <div class="OdnaName" style="outline: none; cursor: inherit;">
                        {{ game.title }}
                    </div>
                    <ul>
                        <li style="list-style: none;">
                            <span><b class="desc1-right-b">Год:</b>
                            <div class="desc1-right-b-two">
                             {{ game.date }}</span>
                            </div>
                         </li>
                        <li style="list-style: none;font-weight: bold;">
                            <span><b class="desc1-right-b">Разработчик:</b>
                                <div class="desc1-right-b-two">
                                {% for developer in game.developer.all %}
                                <a href="{{ developer.get_absolute_url }}">
                                    {{ developer.name }}
                                </a>;
                                {% endfor %}</span>
                            </div>
                        </li>
                        <li style="list-style: none;">
                            <span><b class="desc1-right-b">Издатель:</b>
                                <div class="desc1-right-b-two">
                                {% for publisher in game.publisher.all %}
                                <a href="{{ publisher.get_absolute_url }}">
                                    {{ publisher.name }}
                                    <a />
                                    ;
                                    {% endfor %}
                                </div>
                            </span>
                        </li>
                        <li style="list-style: none;">
                            <span><b class="desc1-right-b">Возрастной рейтинг:</b>
                                <div class="desc1-right-b-two">
                                {% for category in game.category.all %}
                                {{ category.name }}
                                {% endfor %}
                                </div>
                            </span>
                        </li>
                        <li style="list-style: none;"><span><b class="desc1-right-b">Жанр:</b>
                                <div class="desc1-right-b-two">
                                {% for genre in game.genre.all %}
                                {{ genre.name }}
                                {% endfor %}
                                </div>
                            </span>
                        </li>
                        <li style="list-style: none;margin-top: 20px">
                            
                            <form action="{% url 'add_rating' %}" method="post" name="rating">
                                <b class="desc1-right-b">Рейтинг:</b>
                                {% csrf_token %}
                                <input type="hidden" value="{{ game.id }}" name="game">
                                <input type="hidden" value="{{ user.username }}" name="username">
                                <span class="rating">
                                    {% for k, v in star_form.fields.star.choices %}
                                    <input id="rating{{ v }}" type="radio" name="star" value="{{ k }}">
                                    <label for="rating{{ v }}">{{ k }}</label>
                                    {% endfor %}
                                </span>
                                <br>
                                
                            </form>
                            
                        </li>
                        <div class="share-desc" style="list-style: none;margin-left: -225px">
                            <div class="share">
                                <ul class="w3layouts_social_list list-unstyled">
                                    <li>
                                        <a href="#" class="w3pvt_facebook editContent" style="outline: none; cursor: inherit;">
                                            <span class="fa fa-facebook-f" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_twitter editContent" style="outline: none; cursor: inherit;">
                                            <span class="fa fa-twitter" style="outline: none; cursor: inherit;"></span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" class="w3pvt_vk editContent">
                                            <span class="fa fa-vk"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                </div>
            </div>
            <div class="row sub-para-w3layouts mt-5">
                <a class="shop-sing" >
                    О игре {{ game.title }}</a>
                
                <div>
                    <br>
                    {% for image in game.gameshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-game-shots" alt="{{ image.description }}">
                    {% endfor %}
                </div>
                <div class="shop-sing-opis">
                    {{ game.description|safe}}
                </div>
            </div>
            <div class="row">
                <!-- contact form grid -->
                <div class="single-form-left">
                    <!-- contact form grid -->
                    <div class="contact-single">
                        <div class="editContent" style="outline: none; cursor: inherit;">
                            <span style="outline: none; cursor: inherit;">
                                <h6>Количество комментариев: {{ game.reviews_set.count }}</h6>
                            </span><div class="contact-single-comm">Оставить
                            отзыв</div></div>
                        <form action="{% url 'add_review' game.id %}" method="post" class="mt-4" id="formReview">
                            {% csrf_token %}
                            <input type="hidden" name="parent" id="contactparent" value="">
                            <div class="form-group editContent">
                                <label for="contactcomment" class="feedback-game">
                                    Ваш комментарий 
                                </label>
                                <textarea class="form-control-comment border" rows="5" name="text" id="contactcomment" required=""></textarea>
                            </div>
                            <div class="d-sm-flex">
                                <div class="col-sm-6 form-group p-0 editContent">
                                    <label for="contactusername" class="feedback-game">
                                        Имя 
                                    </label>
                                    <input type="text" class="form-control-comment border" name="name" id="contactusername" required="">
                                </div>
                                <div class="col-sm-6 form-group ml-sm-3 editContent">
                                    <label for="contactemail" class="feedback-game">
                                        Email 
                                    </label>
                                    <input type="email" class="form-control-comment border" name="email" id="contactemail" required="">
                                </div>
                            </div>
                            <button type="submit" class="btn-feed">
                                Отправить
                            </button>
                        </form>
                    </div>
                    <!--  //contact form grid ends here -->
                </div>
            </div>
            <!--  //contact form grid ends here -->
            {% for review in game.get_review %}
            <div class="media py-5">
                <img src="{% static 'images/te3.jpg'%}" class="ava" alt="image">
                <div class="media-body mt-4">
                    <div class="mt-0 editContent">
                        {{ review.name }}
                    </div>
                    <div class="mt-2 editContent">
                        {{ review.text }}
                    </div>
                    <a class="review_reply"href="#formReview" onclick="addReview('{{ review.name }}', '{{ review.id }}')">Ответить</a>
                    <br>
                    {% for rew in review.reviews_set.all%}
                    <div class="media mt-5 editContent" style="outline: none; cursor: inherit;">
                        <a class="pr-3" href="#">
                            <img src="{% static 'images/te2.jpg'%}" class="img-avatar" alt="image" style="outline: none; cursor: inherit;">
                        </a>
                        <div class="media-body">
                            <h5 class="mt-0 editContent" style="outline: none; cursor: inherit;">{{rew.name}}</h5>
                            <p class="mt-2 editContent" style="outline: none; cursor: inherit;">{{rew.text}}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <script type="text/javascript">
    function addReview(name, id) {
        document.getElementById('contactparent').value = id;
        document.getElementById('contactcomment').innerText = `${name}, `
    }
    </script>
    {% endblock game%}

templates/games/game_list.html
{% extends 'games/games_base.html' %}
{% block header %} bg1 {% endblock header %}
{% block game %}
<div class="left-ads-display col-lg-9">
    <div class="row games_page_gr">
        <!--
        <iframe src="https://discord.com/widget?id=270935505548476416&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0" sandbox="allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts"></iframe>
        <script src="https://apps.elfsight.com/p/platform.js" defer></script>-->
        
        <div class="elfsight-app-07390897-7d61-481e-9040-10167707b457"></div>
        {% for game in game_list %}
        <div class="col-md-4 product-men">
            <div class="product-shoe-info editContent text-center mt-lg-4">
                <div class="men-thumb-item">
                    <a href="{{ game.get_absolute_url }}">
                        <img src="{{ game.poster.url}}" class="img-fluid" alt="">
                    </a>
                </div>
                <div class="item-info-product">
                    <div class="item-info-product-name">
                        <a href="{{ game.get_absolute_url }}" class="editContent">
                            {{ game.title }}
                        </a>
                    </div>
                    <div class="product_price">
                        <div class="grid-price">
                            <span class="money editContent">
                                {% for genre in game.genre.all %}
                                {{ genre.name }}
                                {% endfor %}
                            </span>
                        </div>
                    </div>
                    <ul class="stars">
                        <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="fa fa-star-half" aria-hidden="true"></span></a></li>
                        <li><a href="#"><span class="" aria-hidden="true"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="grid-img-right mt-4 text-right bg bg1 page-number">
        {% include 'include/pagination.html' %}
    </div>
</div>
{% endblock game %}

templates/games/games_base.html
{% extends 'base.html' %}
{% block content%}
<section class="ab-info-main py-md-5 py-4 editContent" >
		{% block container %}
    	<div class="container-fluid py-md-3">
    {% endblock container %}
        <div class="row">
	    {% block sidebar %}
	        <div class="side-bar col-lg-3 "id="side-bar-script">
	    {% endblock sidebar %}
            {% include 'include/sidebar.html' %}
        </div>
            {% block game %}
            {% endblock game %} 
        </div>
    </div>
</section>
{% endblock content%}

templates/games/genre.html
{% extends 'games/games_base.html'%}
{% load static %}
{% block title %} {{ genre.name }} {% endblock title%}
{% block container %}
<div class="container py-md-3">
    {% endblock container %}
    {% block sidebar %}
    <div class="side-bar col-lg-4">
        {% endblock sidebar %}
        {% block game %}
        <div class="left-ads-display col-lg-8">
            <div class="row">
                <div class="desc1-right col-md-6 pl-lg-4">
                    <h2 class="editContent" style="outline: none; cursor: inherit;">
                        {{ genre.name }}
                        </h3>
                        <h6 class="editContent">
                            <div class="row sub-para-w3layouts mt-5">
                                <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
                                    О жанре {{ genre.name }}
                                </h3>
                            </div>
                        </h6>
                </div>
                <div class="clearfix"></div>
                <p>
                    {{ genre.description}}
                </p>
            </div>
            {% for game in game_list %}
            <div class="col-md-4 product-men">
                <div class="product-shoe-info editContent text-center mt-lg-4">
                    <div class="men-thumb-item">
                        <a href="{{ game.get_absolute_url }}">
                            <img src="{{ game.poster.url}}" class="img-fluid" alt="">
                        </a>
                    </div>
                    <div class="item-info-product">
                        <h4 class="">
                            <a href="{{ game.get_absolute_url }}" class="editContent">
                                {{ game.title }}
                            </a>
                        </h4>
                        <div class="product_price">
                            <div class="grid-price">
                                <span class="money editContent">
                                    {% for genre in game.genre.all %}
                                    {{ genre.name }}
                                    {% endfor %}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <hr>
    <script type="text/javascript">
    function addReview(name, id) {
        document.getElementById('contactparent').value = id;
        document.getElementById('contactcomment').innerText = `${name}, `
    }
    </script>
    {% endblock game%}